name: Terraform 

on: 
  push:
    paths:
      - "terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup configuration
        uses: hashicorp/setup-terraform@v4

      - run: terraform fmt -check
        working-directory: terraform/

      - run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: terraform/

      - run: terraform plan
        working-directory: terraform/
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        

      