name: Test Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret
        run: |
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "Secret exists"
          else
            echo "Secret missing"
          fi